initApi:
    uri: /api/init
    controller: Controller\api\InitController
    httpMethod: [GET]
doc:
    uri: /doc
    controller: Controller\DocController
    httpMethod: [GET]
getStations:
    uri: /api/stations
    controller: Controller\api\Station\StationsController
    httpMethod: [GET]
getStationById:
    uri: '/api/station/{id}'
    controller: Controller\api\Station\StationIdController
    httpMethod: [GET]
getStationStatusById:
    uri: '/api/station/{id}/status'
    controller: Controller\api\Station\StationStatusIdController
    httpMethod: [GET]
getStationsStatus:
    uri: /api/stations/status
    controller: Controller\api\Status\StationsStatusController
    httpMethod: [GET]
